export const metadata = {
  title: "About Page",
  description: "Generated by create next app for about page",
};

export default function AboutLayout({ children }) {
  return <div>{children}</div>;
}
